apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice-back-end
  name: myservice-back-end
spec:
  ports:
    - nodePort: 30945
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: myservice-back-end
  type: LoadBalancer