apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice-back-end
  template:
    metadata:
      labels:
        app: myservice-back-end
    spec:
      containers:
        - image: efrei/myservice-back-end:1
          imagePullPolicy: IfNotPresent
          name: myservice-back-end
      restartPolicy: Always
